FROM node:18-alpine
# Update npm to the latest version
RUN npm install -g npm@latest
# Set the workdir to /app (also creates the /app folder if it does not exists)
WORKDIR /app
# Copy project setup files
COPY ./setup .
# Install all svelte-kit dependencies & adapter for generating static sites
RUN npm install
# Expose port 3000
EXPOSE 3000
# By default we run the dev server
CMD ["npm", "run", "dev"]
#CMD ["npm", "run", "dev", "--host", "0.0.0.0"]