# version: "3.4"
# services:
#   client:
#     image: client
#     restart: on-failure
#     build:
#       context: "."
#       dockerfile: Dockerfile.dev
#     ports:
#       - 3000:3000
#       - 24678:24678
#     volumes:
#       - ./:/usr/src/app
#       - /usr/src/app/node_modules


version: '3'
services:
  web:
    container_name: webxxx
    image: node:16.19.0-alpine3.16
    ports:
      - 8080:8080
    command: npm install && npm run dev
    working_dir: /src
    volumes:
      - ".:/src"
    environment:
      HOST: 0.0.0.0