# # Our Node base image
# FROM node:16.19.0-alpine3.16
# # Set the Node environment to development to ensure all packages are installed
# ENV NODE_ENV development
# # Change our current working directory
# WORKDIR /usr/src/app
# # Copy over `package.json` and lock files to optimize the build process
# COPY ["package.json", "package-lock.json*",  "./"]
# # Install Node modules
# RUN npm install
# # Copy over rest of the project files
# COPY . .
# # Expose port 3000 for the SvelteKit app and 24678 for Vite's HMR
# EXPOSE 3000
# EXPOSE 24678
# # Run `yarn dev` and set the host to 0.0.0.0 so we can access the web app from outside
# CMD ["npm", "run", "dev", "--host", "0.0.0.0"]




FROM node:16.19.0-alpine3.16


WORKDIR /test-app

COPY package.json package-lock.json ./

RUN npm ci
COPY . .
RUN npm run build

CMD npm rebuild esbuild && npm run dev -- --host