services:
  web:
    build: .
    ports:
      - "5173:5173"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    working_dir: "/app"
    volumes:
      - type: bind
        source: ./
        target: /app
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
